[profile.default]
src = "contracts"
test = "forge-test"
out = "out"
cache_path = "forge-cache"

solc_version = "0.8.25"
optimizer = true
optimizer_runs = 1
via_ir = false

# Allow Foundry to resolve Solidity deps from node_modules
libs = ["node_modules", "lib"]

# Explicit remappings for npm-style imports
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@rsksmart/=node_modules/@rsksmart/",
  "@rsksmart/btc-transaction-solidity-helper/=node_modules/@rsksmart/btc-transaction-solidity-helper/",
  "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
rskRegtest = "${REGTEST_RPC_URL}"
rskTestnet = "${TESTNET_RPC_URL}"
rskMainnet = "${MAINNET_RPC_URL}"
