name: Slither Analysis
on: [push]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Use Node.js 20.15.1
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: "20.15.1"

      - name: NPM Login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm config set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN

      - name: Install dependencies
        run: npm ci

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@50d5a8956f2e319df19e6b57539d7e2acb9f8c1e" # v1.5.0
        with:
          version: stable

      - name: Build contracts
        run: forge build --build-info

      - name: Run Slither
        uses: crytic/slither-action@f197989dea5b53e986d0f88c60a034ddd77ec9a8 # v0.4.0
        id: slither
        with:
          sarif: results.sarif
          fail-on: none
          target: .
          slither-args: --filter-paths "node_modules/|src/test-contracts/|src/test/|src/legacy"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@48ab28a6f5dbc2a99bf1e0131198dd8f1df78169 # v3.28.0
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
