name: Slither Analysis
on: [push]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Use Node.js 20.15.1
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: "20.15.1"

      - name: NPM Login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm config set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN

      - name: Install dependencies
        run: npm ci

      - name: Run Slither
        uses: crytic/slither-action@6ef3a33e56de4e8f59488cf60858b5c1bf4967c0 # v0.3.0
        id: slither
        with:
          sarif: results.sarif
          fail-on: none
          target: .
          args: --exclude contracts/safe

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@461ef6c76dfe95d5c364de2f431ddbd31a417628 # v3.26.9
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
