name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 19.6.0
        uses: actions/setup-node@v3
        with:
          node-version: '19.6.0'

      - name: NPM Login
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          sarif: results.sarif
          fail-on: none
          target: .

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
