name: Slither Analysis
on: [push]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js 19.6.0
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '19.6.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Slither
        uses: crytic/slither-action@f197989dea5b53e986d0f88c60a034ddd77ec9a8 # v0.4.0
        id: slither
        with:
          sarif: results.sarif
          fail-on: none
          target: .
          slither-args: --filter-paths "node_modules/"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@48ab28a6f5dbc2a99bf1e0131198dd8f1df78169 # v3.28.0
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
